defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: drafts
    values:
      layout: post
timezone: TR
icon: https://redjournal.us/favicons.png
feed_author_name: Erdi Demir
feed_base: https://redjournal.us
feed_id_authority: https://redjournal.us
