defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: drafts
    values:
      layout: post
timezone: TR/Pacific
icon: https://github.com/erdidemirim/erdidemirim.github.io/blob/main/favicons.png
feed_author_name: Erdi Demir
feed_base: https://redjournal.us
feed_id_authority: https://twitter.com/erdidemir
